### ISSUE TITLE
Problem in understanding inheritance using __call__ 

### ISSUE THREAD

**Issue by akashmahalik** [jayconrod/imp-interpreter#1]
In the file combinators.py
line 104 : left_result = self.left(tokens, pos)
self.left passes the arguments 'tokens' and 'pos' to which function?

I am a newbie.Sorry,if it's a lame doubt

**Comment by jayconrod** [comment]
In that class, `self.left` and `self.right` are other `Parser` objects. So this invokes the `__call__` method of some other subclass in that file.

**Comment by papandadj** [comment]
your blog is down
